version: "3.8"

networks:
  public:
    external: true
  internal:
    external: true

secrets:
  traefik_basic_auth:
    external: true
  traefik_tls_cert:
    external: true
  traefik_tls_key:
    external: true

configs:
  traefik_dynamic:
    file: ./dynamic.yml

services:
  traefik:
    image: traefik:v2.11
    command:
      - --api.dashboard=true
      - --api.insecure=false

      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=public

      - --providers.file=true
      - --providers.file.filename=/etc/traefik/dynamic.yml

      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      - --entrypoints.websecure.address=:443

      - --accesslog=true
      - --log.level=INFO
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public
      - internal
    configs:
      - source: traefik_dynamic
        target: /etc/traefik/dynamic.yml
    secrets:
      - traefik_basic_auth
      - traefik_tls_cert
      - traefik_tls_key
    deploy:
      placement:
        constraints:
          - node.labels.tier == control
      labels:
        - traefik.enable=true

        # Dashboard: https://traefik.sexydad  (sirve en /dashboard/ y /api)
        - traefik.http.routers.traefik.rule=Host(`traefik.sexydad`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.tls=true

        # En Swarm: define explícitamente el puerto del backend (evita "port is missing")
        - traefik.http.routers.traefik.service=traefik-dashboard
        - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
        - traefik.http.services.traefik-traefik.loadbalancer.server.port=8080


        # Mitigación mínima: LAN only + BasicAuth
        - traefik.http.routers.traefik.middlewares=lan-whitelist@docker,traefik-auth@docker
        - traefik.http.middlewares.lan-whitelist.ipwhitelist.sourcerange=192.168.80.0/24
        - traefik.http.middlewares.traefik-auth.basicauth.usersfile=/run/secrets/traefik_basic_auth
